Capistrano::Configuration.instance.load do

  set :omeka_branch, "master" unless exists?(:omeka_branch)

  def git_clone(hash, directory)
    hash.each do |name, location|
      run "cd #{current_path}/#{directory} && rm -rf #{name}"
      run "cd #{current_path}/#{directory} && git clone #{location} --quiet"
    end
  end

  namespace :omeka do
    desc '|OmekaRecipes| Ensure the archive directory has write permissions'
    task :fix_archive_permissions do
      # This _should_ actually change the permissions of the archive directory to
      # be the owner of process running httpd/apache2 daemon.
      run "chmod -R 777 #{current_path}/archive"
    end

    desc '|OmekaRecipes| Rename files'
    # Omeka stages these files in its repo
    task :rename_files do
      run "cd #{current_path} && mv .htaccess.changeme .htaccess"
      run "cd #{current_path}/application/config && mv config.ini.changeme config.ini"
    end

    desc '|OmekaRecipes| Move the archive directory out of the way'
    task :move_archive_dir do
      run "mv #{current_path}/archive #{current_path}/archive_deleteme"
    end

    desc '|OmekaRecipes| Link the archive directoy for the project'
    task :link_archive_dir, :except => {:no_release => true} do
      run "cd #{current_path} && ln -snf #{shared_path}/archive"
    end

    desc '|OmekaRecipes| Add the db.ini to the shared directory'
    task :db_ini do
      run "touch #{shared_path}/db.ini"
    end

    desc '|OmekaRecipes| Move a pristine copy of the archives/files directory to the shared_path'
    task :move_files_to_shared, :except => { :no_release => true } do
      #run "touch #{shared_path}/db.ini"
      run "mkdir -p #{shared_path}/application/logs/"
      run "touch #{shared_path}/application/logs/erros.log"
    end

    desc '|OmekaRecipes| Deploy the plugins defined in the plugins hash'
    task :get_plugins do
      git_clone(plugins, 'plugins')
    end

    desc '|OmekaRecipes| Deploy the themes defined in the themes hash'
    task :get_themes do
      git_clone(themes, 'themes')
    end

    namespace :maintenance do
      desc <<-DESC
        |OmekaRecipes| Add a maitenance page for visitors. Disables your Omeka
        isntance by writing a "#{maintenance_basename}.html" file to each web
        server. The servers must be configured to detect the presence of the file,
        and if it is present, display the maintenance page instead of performaning
        the request.

          $ cap omeka:maintenance:start \\
            REASON="hardware upgrade" \\
            UNTIL="12pm EST"

        You can use a different template for the maintenace page by setting the
        :maintenace_template_path variable in your deploy.rb. The template file
        should either be a plaintext or an erb file.
      DESC
      task :start, :roles => :web, :except => { :no_release => true } do
        require 'erb'
        on_rollback { run "rm -f #{shared_path}/system/maintenance.html" }

        warn <<-HTACCESS
          # Please add something like this to your site's Apache htaccess to redirect users to the maintenance page.
          # More Info: http://www.shiftcommathree.com/articles/make-your-rails-maintenance-page-respond-with-a-503

          ErrorDocument 503 /system/maintenance.html
          RewriteEngine On
          RewriteCond %{REQUEST_URI} !\.(css|gif|jpg|png)$
          RewriteCond %{DOCUMENT_ROOT}/system/maintenance.html -f
          RewriteCond %{SCRIPT_FILENAME} !maintenance.html
          RewriteRule ^.*$  -  [redirect=503,last]
        HTACCESS

        reason = ENV['REASON']
        deadline = ENV['UNTIL']

        template = File.read(maintenance_template_path)
        result = ERB.new(template).result(binding)

        put result, "#{shared_path}/system/maintenance.html", :mode => 0644
      end
    end

    desc <<-DESC
      Enables the application web-accessible again. Removes the \n
      "maintenance.html" page generated by deploy:maitenance:start,
      which, (if your server is configured properly) will make Omeka web-
      accessible again.
    DESC
    task :end, :roles => :web, :except => { :no_release => true } do
      run "rm -f #{shared_path}/system/#{maintenance_basename}.html"
    end

  end

  after 'deploy:cold', 'omeka:fix_archive_permissions', 'omeka:move_archive_dir'
  after 'deploy:setup', 'omeka:move_files_to_shared'
  #before 'deploy:create_symlink', 'omeka:move_archive_dir'
  #after 'deploy:create_symlink', 'omeka:link_archive_dir'
  after 'deploy', 'omeka:get_themes', 'omeka:get_plugins', 'omeka:rename_files'

end
